openapi: "3.0.3"
info:
  title: "work_order_system API"
  description: "work_order_system API"
  version: "1.0.0"
servers:
  - url: "https://work_order_system"
tags:
  - name: "登录"
paths:
  /api/login/login:
    post:
      summary: "登录"
      description: ""
      operationId: ""
      parameters:
        - name: "username"
          in: "query"
          required: true
          schema:
            type: "string"
        - name: "password"
          in: "query"
          required: true
          schema:
            type: "string"
      responses:
        "200":
          description: "OK"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ResultMessage"
components:
  schemas:
    Meta:
      type: "object"
      properties:
        success:
          type: "boolean"
        code:
          type: "integer"
          format: "int32"
        timestamp:
          type: "string"
          format: "date-time"
        msg:
          type: "string"
    JSONArray:
      type: "object"
      properties: { }
    PageData:
      type: "object"
      properties:
        pageNumber:
          type: "integer"
          format: "int32"
        pageSize:
          type: "integer"
          format: "int32"
        total:
          type: "integer"
          format: "int64"
        list:
          $ref: "#/components/schemas/JSONArray"
    ScrollData:
      type: "object"
      properties:
        scrollId:
          type: "string"
        list:
          $ref: "#/components/schemas/JSONArray"
    JSONObject:
      type: "object"
      properties: { }
    ResultMessage:
      type: "object"
      properties:
        meta:
          $ref: "#/components/schemas/Meta"
        page:
          $ref: "#/components/schemas/PageData"
        scroll:
          $ref: "#/components/schemas/ScrollData"
        data:
          $ref: "#/components/schemas/JSONObject"
        list:
          $ref: "#/components/schemas/JSONArray"
        value:
          type: "string"
